language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer install
  - cp .env.travis .env
  - php artisan key:generate
  - touch database/database.sqlite
  - php artisan migrate
